package serve

import "net/http"

// routes is this server's bare mux, and the whole of it: every path this
// server answers, in one file a reader can scan rather than a section of the
// one that assembles the server. A hub mounts several of them behind one set
// of middleware, so auth, CSRF and logging run once per request rather than
// once per runtime.
func (s *Server) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /", s.index)
	mux.HandleFunc("GET /sessions/{id}", s.index)
	mux.HandleFunc("GET /assets/logo-wordmark.svg", s.logoWordmark)
	mux.HandleFunc("GET /provider-setup", s.providerSetupStatus)
	mux.HandleFunc("POST /provider-setup", s.providerSetupSave)
	mux.HandleFunc("GET /events", s.events)
	mux.HandleFunc("GET /events/replay", s.eventsReplay)
	mux.HandleFunc("GET /history", s.history)
	mux.HandleFunc("GET /usage", s.usage)
	mux.HandleFunc("GET /context", s.context)
	mux.HandleFunc("GET /adjudications", s.adjudications)
	mux.HandleFunc("GET /browser/tabs", s.browserTabs)
	mux.HandleFunc("POST /browser/open", s.browserOpen)
	s.registerExecutionGraphRoutes(mux)
	mux.HandleFunc("POST /context/window", s.setContextWindow)
	mux.HandleFunc("POST /submit", s.submit)
	s.registerExtensionRoutes(mux)
	s.registerPluginRoutes(mux)
	s.registerThemeRoutes(mux)
	s.registerAppearanceRoutes(mux)
	s.registerSurfaceRoutes(mux)
	s.registerInboxRoutes(mux)
	s.registerJobRoutes(mux)
	s.registerProviderRoutes(mux)
	s.registerRoleRoutes(mux)
	s.registerStorageRoutes(mux)
	s.registerWelcomeRoutes(mux)
	mux.HandleFunc("POST /cancel", s.cancel)
	mux.HandleFunc("POST /approve", s.approve)
	mux.HandleFunc("POST /plan-decision", s.planDecision)
	mux.HandleFunc("POST /plan", s.plan)
	mux.HandleFunc("POST /preset", s.preset)
	mux.HandleFunc("POST /model", s.model)
	mux.HandleFunc("POST /effort", s.effort)
	mux.HandleFunc("POST /compact", s.compact)
	s.registerCompactionRoutes(mux)
	mux.HandleFunc("POST /new", s.newSession)
	mux.HandleFunc("POST /rewind", s.rewind)
	mux.HandleFunc("POST /rewind/prepare", s.rewindPrepare)
	mux.HandleFunc("POST /rewind/commit", s.rewindCommit)
	mux.HandleFunc("POST /rewind/undo", s.rewindUndo)
	mux.HandleFunc("POST /rewind/file/prepare", s.fileRevertPrepare)
	mux.HandleFunc("POST /rewind/file/commit", s.fileRevertCommit)
	mux.HandleFunc("POST /summarize", s.summarize)
	mux.HandleFunc("POST /tool-approval-mode", s.toolApprovalMode)
	mux.HandleFunc("POST /auto-approve-tools", s.autoApproveTools)
	mux.HandleFunc("POST /bypass", s.bypass)
	mux.HandleFunc("POST /goal", s.goal)
	mux.HandleFunc("POST /answer", s.answer)
	mux.HandleFunc("POST /resume", s.resume)
	mux.HandleFunc("POST /forget", s.forget)
	mux.HandleFunc("POST /prompt/refine", s.refinePrompt)
	mux.HandleFunc("GET /checkpoints", s.checkpoints)
	mux.HandleFunc("GET /branches", s.branches)
	mux.HandleFunc("GET /models", s.models)
	mux.HandleFunc("POST /extensions/reload", s.reloadExtensionsHTTP)
	mux.HandleFunc("GET /status", s.status)
	mux.HandleFunc("GET /balance", s.balance)
	mux.HandleFunc("GET /sessions", s.sessions)
	mux.HandleFunc("GET /trajectory", s.trajectory)
	mux.HandleFunc("GET /memory", s.memories)
	mux.HandleFunc("POST /memory/forget", s.forgetMemory)
	mux.HandleFunc("POST /memory/save", s.saveMemory)
	mux.HandleFunc("GET /memory/revisions", s.memoryRevisions)
	mux.HandleFunc("POST /memory/restore", s.restoreMemory)
	s.registerShellRoutes(mux)
	s.registerBoundaryRoutes(mux)
	mux.HandleFunc("GET /network", s.network)
	mux.HandleFunc("POST /network", s.saveNetwork)
	mux.HandleFunc("POST /network/diagnose", s.diagnoseNetwork)
	mux.HandleFunc("GET /hooks", s.hooks)
	mux.HandleFunc("POST /hooks", s.saveHooks)
	mux.HandleFunc("POST /hooks/dry-run", s.dryRunHook)
	mux.HandleFunc("GET /skills", s.skills)
	mux.HandleFunc("POST /skills/enabled", s.skillEnabled)
	mux.HandleFunc("GET /slash", s.slash)
	mux.HandleFunc("GET /complete", s.complete)
	mux.HandleFunc("GET /capability-scope", s.capabilityScopeHandler)
	mux.HandleFunc("GET /mcp", s.mcp)
	mux.HandleFunc("POST /mcp/reconnect", s.mcpReconnect)
	mux.HandleFunc("POST /mcp/enabled", s.mcpEnabled)
	mux.HandleFunc("POST /mcp/load", s.mcpLoad)
	mux.HandleFunc("POST /mcp/parse", s.mcpParse)
	mux.HandleFunc("POST /mcp/install", s.mcpInstall)
	mux.HandleFunc("POST /mcp/remove", s.mcpRemove)
	mux.HandleFunc("GET /account", s.account)
	mux.HandleFunc("POST /account/login", s.accountLogin)
	mux.HandleFunc("POST /account/poll", s.accountPoll)
	mux.HandleFunc("POST /account/logout", s.accountLogout)
	mux.HandleFunc("GET /workspaces", s.workspaces)
	mux.HandleFunc("POST /workspace", s.workspace)
	mux.HandleFunc("GET /todos", s.todos)
	mux.HandleFunc("GET /changes", s.changes)
	mux.HandleFunc("GET /changes/diff", s.changeDiff)
	mux.HandleFunc("GET /workspace/files", s.workspaceFiles)
	mux.HandleFunc("GET /workspace/file", s.workspaceFileRead)
	mux.HandleFunc("GET /workspace/image", s.workspaceImage)
	mux.HandleFunc("PUT /workspace/file", s.workspaceFileWrite)
	mux.HandleFunc("POST /workspace/editor", s.openInEditor)
	mux.HandleFunc("POST /attachments", s.attachments)
	mux.HandleFunc("POST /drop", s.drop)
	mux.HandleFunc("POST /delete-session", s.deleteSession)
	return mux
}
